export const DATE_UPDATED = "DATE_UPDATED";
export const RATES_UPDATED = "RATES_UPDATED";
export const NEW_OPERATION = "NEW_OPERATION";
export const RELOAD_OPERATIONS = "RELOAD_OPERATIONS";
export const CURRENCY_CHANGED = "CURRENCY_CHANGED";
export const SET_TOTAL_AMOUNT = "SET_TOTAL_AMOUNT";
